require:
  - rubocop-rspec
  - rubocop-rake

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Layout/LineLength:
  Max: 120
Naming/FileName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
