require:
  - rubocop-rspec
  - rubocop-rake

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Style/ModuleFunction:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/Documentation:
  Enabled: false
