name: Active Record head

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [ 3.0, 3.1, 3.2, 3.3, head ]
    env:
      BUNDLE_GEMFILE: gemfiles/activerecord_head.gemfile
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run tests
      # Allow tests to run on Active Record head without failing the pipeline
      run: bundle exec rspec || true
